#!/bin/bash
set -euxo pipefail

INITIAL_USER=pine
INITIAL_PASSWORD=1111

if ! getent passwd $INITIAL_USER; then
    useradd -m -G wheel,dialout,video,audio,input $INITIAL_USER
    printf "$INITIAL_PASSWORD" | passwd --stdin $INITIAL_USER
fi

systemctl disable pine-first-boot.service
